services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskManager

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  task-manager:
    depends_on:
      - mongodb
      - db
    image: emorres25/task-manager
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.data.mongodb.uri" : "mongodb://admin:password@mongodb:27017/taskManager?authSource=admin",
              "spring.datasource.url" : "jdbc:postgresql://db:5432/taskManager"
            }'
    links:
      - mongodb
      - db
